# main.yml;

name: workflow 

# Allow repository modyfication;
permissions:
  contents: write
  pull-requests: write
  packages: write

on:
  # Allow to re-use this jobs;
  workflow_call:

jobs:

# -----------------
# SEMVER 
# -----------------

  semver:
    uses: utilizable/github-actions-semver-tagging/.github/workflows/tagging.yml@feat/output

# -----------------
# ANSIBLE 
# -----------------

  ansible:
    # Restrict to manual startup; 
    if: ${{ (github.event_name == 'workflow_dispatch' && github.actor) }}
    uses: ./.github/workflows/ansible.yml
