# main.yml;

name: workflow 

# Allow repository modyfication;
permissions:
  contents: write
  pull-requests: write
  packages: write

on:
  # Trigger automaticly;  
  push:
  # Trigger manually;
  workflow_dispatch:
    inputs:
      ssh_host:
        description: 'SSH host ( ip / fqdn name )'     
        required: true
      ssh_port:
        description: 'SSH port'
        required: true
      ssh_user:
        description: 'SSH user'
        required: true
      ssh_pass:
        description: 'SSH password'
        required: true

jobs:

# -----------------
# SEMVER 
# -----------------

  semver:
    uses: utilizable/github-actions-semver-tagging/.github/workflows/tagging.yml@feat/output

# -----------------
# ANSIBLE 
# -----------------

  ansible:
    # Restrict to manual startup; 
    if: ${{ (github.event_name == 'workflow_dispatch' && github.actor) }}
    uses: ./.github/workflows/ansible.yml
